server {
    # nginx listens on port 80 inside its own container (standard
    # default web server port).
    listen 80;

    location / {
        # Serves your actual built React app files.
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8080/api/;
    }

    # location /reg {
    #     proxy_pass http://backend:8080/reg;
    # }

    # location /login {
    #     proxy_pass http://backend:8080/login;
    # }
}